name: Attendance

on:
  schedule:
    - cron: '0 8 * * *'  # Log attendance everyday at 08:00 UTC

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Attendance
      run: |
        echo "Present: $(date -u +"%Y-%m-%d %H:%M:%S") (UTC)" >> attendance.txt

    - name: Commit Changes
      run: |
        git config user.name "prinnccee"
        git config user.email "prinnccee@users.noreply.github.com"
        git add attendance.txt
        git commit -m "👑 attendance: $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
        git push
